export const storeProducts = [
    {
      id: 1,
      title: 'Destaques da Semana!',
      name: "BICICLETA GTS ARO 29",
      img: "img/product-1.png",
      price: 1240,
      company: "GTSM1",
      shortDescription:'BICICLETA GTSM1 É IDEAL PARA QUEM QUER COMEÇAR NO MOUNTAIN BIKE, TRILHAS LEVES E USO URBANO.' ,
      info:
        "BICICLETA GTSM1 É IDEAL PARA QUEM QUER COMEÇAR NO MOUNTAIN BIKE, TRILHAS LEVES E USO URBANO. SÃO 4 TIPOS DE TAMANHOS DE QUADRO E CORES PARA VOCÊ ESCOLHER, O PESO TOTAL DA BIKE É DE 15.4KG MONTADA. A BIKE É DIRETA DA FÁBRICA OFICIAL COM MAIS DE 23 ANOS NO MERCADO E GARANTIA EXCLUSIVA COM SUPORTE DIFERENCIADO. SUPORTA ATÉ 120KGS.",
      inCart: true,
      count: 0,
      total: 0
    },
    {
      id: 2,
      title: 'Destaques da Semana!',
      name: "BICICLETA GTS ARO 29",
      img: "img/product-1.png",
      price: 1240,
      company: "GTSM1",
      shortDescription:'BICICLETA GTSM1 É IDEAL PARA QUEM QUER COMEÇAR NO MOUNTAIN BIKE, TRILHAS LEVES E USO URBANO.' ,
      info:
        "BICICLETA GTSM1 É IDEAL PARA QUEM QUER COMEÇAR NO MOUNTAIN BIKE, TRILHAS LEVES E USO URBANO. SÃO 4 TIPOS DE TAMANHOS DE QUADRO E CORES PARA VOCÊ ESCOLHER, O PESO TOTAL DA BIKE É DE 15.4KG MONTADA. A BIKE É DIRETA DA FÁBRICA OFICIAL COM MAIS DE 23 ANOS NO MERCADO E GARANTIA EXCLUSIVA COM SUPORTE DIFERENCIADO. SUPORTA ATÉ 120KGS.",
      inCart: false,
      count: 0,
      total: 0
    },
    {
      id: 3,
      title: 'Destaques da Semana!',
      name: "BICICLETA9",
      img: "img/product-1.png",
      price: 1240,
      company: "GTSM1",
      shortDescription:'BICICLETA GTSM1 É IDEAL PARA QUEM QUER COMEÇAR NO MOUNTAIN BIKE, TRILHAS LEVES E USO URBANO.' ,
      info:
        "BICICLETA GTSM1 É IDEAL PARA QUEM QUER COMEÇAR NO MOUNTAIN BIKE, TRILHAS LEVES E USO URBANO. SÃO 4 TIPOS DE TAMANHOS DE QUADRO E CORES PARA VOCÊ ESCOLHER, O PESO TOTAL DA BIKE É DE 15.4KG MONTADA. A BIKE É DIRETA DA FÁBRICA OFICIAL COM MAIS DE 23 ANOS NO MERCADO E GARANTIA EXCLUSIVA COM SUPORTE DIFERENCIADO. SUPORTA ATÉ 120KGS.",
      inCart: false,
      count: 0,
      total: 0
    },
    {
      id: 4,
      title: 'Destaques da Semana!',
      name: "BICICLETA GTS ARO 29",
      img: "img/product-1.png",
      price: 1240,
      company: "GTSM1",
      shortDescription:'BICICLETA GTSM1 É IDEAL PARA QUEM QUER COMEÇAR NO MOUNTAIN BIKE, TRILHAS LEVES E USO URBANO.' ,
      info:
        "BICICLETA GTSM1 É IDEAL PARA QUEM QUER COMEÇAR NO MOUNTAIN BIKE, TRILHAS LEVES E USO URBANO. SÃO 4 TIPOS DE TAMANHOS DE QUADRO E CORES PARA VOCÊ ESCOLHER, O PESO TOTAL DA BIKE É DE 15.4KG MONTADA. A BIKE É DIRETA DA FÁBRICA OFICIAL COM MAIS DE 23 ANOS NO MERCADO E GARANTIA EXCLUSIVA COM SUPORTE DIFERENCIADO. SUPORTA ATÉ 120KGS.",
      inCart: false,
      count: 0,
      total: 0
      },
      {
        id: 5,
        title: 'Destaques da Semana!',
        name: "BICICLETA GTS ARO 29",
        img: "img/product-3.png",
        price: 1240,
        company: "GTSM1",
        shortDescription:'BICICLETA GTSM1 É IDEAL PARA QUEM QUER COMEÇAR NO MOUNTAIN BIKE, TRILHAS LEVES E USO URBANO.' ,
        info:
          "BICICLETA GTSM1 É IDEAL PARA QUEM QUER COMEÇAR NO MOUNTAIN BIKE, TRILHAS LEVES E USO URBANO. SÃO 4 TIPOS DE TAMANHOS DE QUADRO E CORES PARA VOCÊ ESCOLHER, O PESO TOTAL DA BIKE É DE 15.4KG MONTADA. A BIKE É DIRETA DA FÁBRICA OFICIAL COM MAIS DE 23 ANOS NO MERCADO E GARANTIA EXCLUSIVA COM SUPORTE DIFERENCIADO. SUPORTA ATÉ 120KGS.",
        inCart: false,
        count: 0,
        total: 0
      },
      {
        id: 6,
        title: 'Destaques da Semana!',
      name: "BICICLETA GTS ARO 29",
      img: "img/product-2.png",
      price: 1240,
      company: "GTSM1",
      shortDescription:'BICICLETA GTSM1 É IDEAL PARA QUEM QUER COMEÇAR NO MOUNTAIN BIKE, TRILHAS LEVES E USO URBANO.' ,
      info:
        "BICICLETA GTSM1 É IDEAL PARA QUEM QUER COMEÇAR NO MOUNTAIN BIKE, TRILHAS LEVES E USO URBANO. SÃO 4 TIPOS DE TAMANHOS DE QUADRO E CORES PARA VOCÊ ESCOLHER, O PESO TOTAL DA BIKE É DE 15.4KG MONTADA. A BIKE É DIRETA DA FÁBRICA OFICIAL COM MAIS DE 23 ANOS NO MERCADO E GARANTIA EXCLUSIVA COM SUPORTE DIFERENCIADO. SUPORTA ATÉ 120KGS.",
      inCart: false,
      count: 0,
      total: 0
      },
    {
      id: 7,
      title: 'Destaques da Semana!',
      name: "BICICLETA GTS ARO 29",
      img: "img/product-3.png",
      price: 1240,
      company: "GTSM1",
      shortDescription:'BICICLETA GTSM1 É IDEAL PARA QUEM QUER COMEÇAR NO MOUNTAIN BIKE, TRILHAS LEVES E USO URBANO.' ,
      info:
        "BICICLETA GTSM1 É IDEAL PARA QUEM QUER COMEÇAR NO MOUNTAIN BIKE, TRILHAS LEVES E USO URBANO. SÃO 4 TIPOS DE TAMANHOS DE QUADRO E CORES PARA VOCÊ ESCOLHER, O PESO TOTAL DA BIKE É DE 15.4KG MONTADA. A BIKE É DIRETA DA FÁBRICA OFICIAL COM MAIS DE 23 ANOS NO MERCADO E GARANTIA EXCLUSIVA COM SUPORTE DIFERENCIADO. SUPORTA ATÉ 120KGS.",
      inCart: false,
      count: 0,
      total: 0
    },
    {
      id: 8,
      title: 'Destaques da Semana!',
      name: "BICICLETA GTS ARO 29",
      img: "img/product-2.png",
      price: 1240,
      company: "GTSM1",
      shortDescription:'BICICLETA GTSM1 É IDEAL PARA QUEM QUER COMEÇAR NO MOUNTAIN BIKE, TRILHAS LEVES E USO URBANO.' ,
      info:
        "BICICLETA GTSM1 É IDEAL PARA QUEM QUER COMEÇAR NO MOUNTAIN BIKE, TRILHAS LEVES E USO URBANO. SÃO 4 TIPOS DE TAMANHOS DE QUADRO E CORES PARA VOCÊ ESCOLHER, O PESO TOTAL DA BIKE É DE 15.4KG MONTADA. A BIKE É DIRETA DA FÁBRICA OFICIAL COM MAIS DE 23 ANOS NO MERCADO E GARANTIA EXCLUSIVA COM SUPORTE DIFERENCIADO. SUPORTA ATÉ 120KGS.",
      inCart: false,
      count: 0,
      total: 0
    }
  ];

  
  export const detailProduct = {
    id: 1,
    name: "BICICLETA GTS ARO 29",
    img: "img/product-1.png",
    price: 1299,
    company: "GTSM1",
    info:
    "BICICLETA GTSM1 É IDEAL PARA QUEM QUER COMEÇAR NO MOUNTAIN BIKE, TRILHAS LEVES E USO URBANO. SÃO 4 TIPOS DE TAMANHOS DE QUADRO E CORES PARA VOCÊ ESCOLHER, O PESO TOTAL DA BIKE É DE 15.4KG MONTADA. A BIKE É DIRETA DA FÁBRICA OFICIAL COM MAIS DE 23 ANOS NO MERCADO E GARANTIA EXCLUSIVA COM SUPORTE DIFERENCIADO. SUPORTA ATÉ 120KGS.",
    inCart: false,
    count: 0,
    total: 0
  };